### PR TITLE
site data and schema for broward

### PR DESCRIPTION
**Pull request by abrahamq**

### CODE REVIEW

**Comment by abrahamq** [comment]
need some guidance on how to test locally? 

Thanks!

**Comment by tomasholderness** [comment]
@abrahamq -> @ojha-url discovered the sites have names so he's going to add those in.

**Comment by tomasholderness** [comment]
@abrahamq - re testing. There currently aren't any tests for infrastructure data. So we should probably make some.

See https://github.com/urbanriskmap/cognicity-schema/issues/49

**Comment by abrahamq** [comment]
I tried to run the ./build/sh script but couldn't figure out how to make the password prompts go away? Are you using peer authentication for postgres or how do you manage this?

**Comment by tomasholderness** [comment]
@abrahamq - yes I'm using a ~/.pgpass file. I will make a note to document this in the README.md

https://www.postgresql.org/docs/current/static/libpq-pgpass.html

**Review by tomasholderness — APPROVED** [review]

**Comment by tomasholderness** [comment]
@abrahamq - happy for me to delete the branch?

**Comment by abrahamq** [comment]
Thanks! Yup sounds good to delete this branch.

**Pull request merged**
