### PR TITLE
Merge dev branch to master forming v3.0 RC

### PR DESCRIPTION
**Pull request by tomasholderness**
New schema for version 3.0

### CODE REVIEW

**Comment by matthewberryman** [comment]
I've added a city to watersensor metadata, as I figure that's useful when it comes time to extract data from the database. I had a peek at qlue and there the city column is named qlue_city - perhaps just call it city for consistency with what I've done with the watersensor metadata column and because it's a bit tautological wrt the table name anyway.

**Comment by tomasholderness** [comment]
@matthewberryman the column `qlue_city` is named that way because the city delineation comes from Qlue. We have no control over it and it is separate to the CogniCity definition of city.

Other tables in the cognicity and other schema may have the word city, but I want to be clear that this is a value provided by the data source and not one that is provided by CogniCity. A little pedantic perhaps, but I think better to be clear.

**Comment by matthewberryman** [comment]
@talltom noted - let's leave as is (you could translate it on the fly but that's too inelegant). I will get this schema from master applied today (AEDT) once I've wrapped up the image conversion code.

**Comment by matthewberryman** [comment]
Ok I have a RDS snapshot (cognicity-v3 in ap-southeast-1) built from this, as that's quick to do, however:
* I have left our (not-quite-)prod and dev environments pointing to the old one as it was, as I know you've got card testing stuff in there, and it's a reasonable amount of work to swap the database out, so I'd prefer to leave this until launch (thus you'll have to catch up with any changes manually yourself). Also
* Looks like you've yet to fix https://github.com/urbanriskmap/cognicity-schema/issues/12 
 ? I guess I will need to build a new snapshot when that's fixed.
Anyway, let me know when you're ready to go and if you're happy to swap to a blank one on launch or if I need to migrate data over (better to migrate data than try and patch up anything manually as you want to be guaranteed of getting all schema changes).

**Pull request merged**
